GET http://localhost:3001/api/blogs/

###

POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "title" : "Here we go",
    "author" : "John Doe",
    "url": "http://google.com",
    "likes": 5
}