POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title" : "another blog test",
    "author" : "James Doe",
    "url": "http://google.ca",
    "likes": 8
}

###

GET http://localhost:3003/api/blogs/