POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title" : "testing a note for test",
    "author" : "James Doe",
    "url": "http://google.ca",
    "likes": 8,
    "userId": "6785b1809c9fe757d641e755"
}

###

GET http://localhost:3003/api/blogs/

###
GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/login/
Content-Type: application/json

{
    "username": "charizard",
    "password": "pokemon"
}


###
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoYXJpemFyZCIsImlkIjoiNjc4ODE5ODA3Mjc0ZmE4NjE1ZTMxMDU1IiwiaWF0IjoxNzM3MTU4NjQ5fQ.HokE2u1B-v0kABOXUg4HrmnmXuE406rtFwxDCXpktMk

{
  "title": "Understanding JavaScript Closures",
  "author": "Jane Doe",
  "url": "https://example.com/javascript-closures",
  "likes": 42
}

### 
GET http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoYXJpemFyZCIsImlkIjoiNjc4ODE5ODA3Mjc0ZmE4NjE1ZTMxMDU1IiwiaWF0IjoxNzM3MTU4NjQ5fQ.HokE2u1B-v0kABOXUg4HrmnmXuE406rtFwxDCXpktMk